source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'OpenEye'
workspace 'OpenEye'

pod 'FXBlurView', :git => 'https://github.com/nicklockwood/FXBlurView.git'